### PR TITLE
chore: patch package gesture handler

### PR DESCRIPTION
**Pull request by ayushtom**

### CODE REVIEW

**Review by ugur-eren — APPROVED** [review]
I don't get why we change the isEqual implemention to a custom one, was there an error with lodash version?
Also we recently moved from npm to yarn, `postinstall-postinstall` package can optionally be installed.
Other than that LGTM

**Comment by ayushtom** [comment]
https://github.com/software-mansion/react-native-gesture-handler/pull/2916

This was an error coming on an ios device (not simulator) so i looked into it and saw that software mansion team is also removing this too from their code if we do too then this error will also go away.  The error comes from this specific function inside lodash itself.

Screenshot 2024-05-24 at 3 03 50 PM

**Comment by ayushtom** [comment]
https://github.com/software-mansion/react-native-gesture-handler/pull/2916

This was an error coming on an ios device (not simulator) so i looked into it and saw that software mansion team is also removing this too from their code so i decided that if we do too then this error will also go away. The error comes from this specific function inside lodash itself.

Screenshot 2024-05-24 at 3 03 50 PM

**Comment by ayushtom** [comment]
I would need a test for ios device and android for this one tho. 
The earlier build errors didn't come on my personal device and simulator hence this might be needed

**Comment by ugur-eren** [comment]
Thanks for the PR! I've just added postinstall package for yarn and merged.

**Pull request merged**
