### PR TITLE
fix:Added favicon and a title for a more professional look

### PR DESCRIPTION
**Pull request by Shoetan**
Closes: https://github.com/keep-starknet-strange/joyboy/issues/88

## Summary of Changes

1. **Downloaded the logo from the resource folder**
   - Located the logo file in the project's resource folder.

2. **Created an .ico file from the image**
   - Converted the logo image to an .ico file format for compatibility.

3. **Replaced the favicon in `manifest.json` with the newly created .ico image**
   - Updated the `manifest.json` to use the new .ico file as the favicon.

4. **Installed `react-helmet` package to manage changes to the document head**
   - Added `react-helmet` to the project to facilitate easy management of the document head, like the page title and subsequent seo tactics.
Screenshot 2024-05-30 at 18 35 32

### CODE REVIEW

**Review by ugur-eren — CHANGES_REQUESTED** [review]
The most important title tag is the one at the index.html file. It should be changed, not the App.tsx.
Can you please remove the changes in the App.tsx, and do those changes at the [index.html](https://github.com/keep-starknet-strange/joyboy/blob/3796b931771932ab2c736b19f78abde3aa331d63/website/public/index.html#L27) file?

**Comment by Shoetan** [comment]
Thank you @ugur-eren for your comments I will implement the changes requested. For the favicon I actually did use favicon.io to generate it .

**Comment by ugur-eren** [comment]
@Shoetan favicon.io also provides icons for apple touch etc. we can use those images too:

```html
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/site.webmanifest">
```

**Review by ugur-eren — APPROVED** [review]
Thanks for the work!

**Pull request merged**
