### PR TITLE
ci: add typo detection tool

### PR DESCRIPTION
**Pull request by goofylfg**
Time spent on this PR: 1h

-  use [typos-action](https://github.com/marketplace/actions/typos-action) detect typos in github action
- fixed all checked typos && test github action
- Exclude some false postive word, please refer to the configuration file for details. like.
```
error: `ba` should be `by`, `be`
  --> ./onchain/src/bip340.cairo:68:5
   |
68 |     ba.append_word(rx.low.into(), 16);
   |     ^^
   |
error: `ba` should be `by`, `be`
  --> ./onchain/src/bip340.cairo:70:5
   |
70 |     ba.append_word(px.high.into(), 16);
```

**Result**
image

### CODE REVIEW

**Comment by ugur-eren** [comment]
@maciejka do we need this?

**Comment by goofylfg** [comment]
I think adding automated tools to check typos is a once and for all way to avoid many subsequent small PRs

**Comment by maciejka** [comment]
If it does not generate to many false positives.

**Review by ugur-eren — APPROVED** [review]
Doesn't seems like creates false positives. LGTM

**Pull request merged**
