### PR TITLE
SNIP-06

### PR DESCRIPTION
**Pull request by maciejka**

### CODE REVIEW

**Comment by mubarak23** [comment]
add snforge prank so that calling contract will be account contract and a demo user created via contract_address_const::<0>()

```

  #[test]
    fn is_valid_signature_success() {
        // private key: 70aca2a9ab722bd56a9a1aadae7f39bc747c7d6735a04d677e0bc5dbefa71d47
        // just for testing, do not use for anything else
        let public_key =
            0xd6f1cf53f9f52d876505164103b1e25811ec4226a17c7449576ea48b00578171_u256;

        let account_class = declare_account();
        let account = deploy_account(account_class, public_key);
        // TODO: cleanup

         snf::start_prank(CheatTarget::One(account.contract_address), contract_address_const::<0>());

        let account = ISRC6Dispatcher { contract_address: account.contract_address};

        let hash = 123;

        let r = 1_u256;
        let s = 2_u256;

        let mut signature = Default::default();
        r.serialize(ref signature);
        s.serialize(ref signature);

        assert!(account.is_valid_signature(hash, signature) == starknet::VALIDATED);
        snf::stop_prank(CheatTarget::One(account.contract_address));
    }

```

**Comment by maciejka** [comment]
How does this fix the test?

**Comment by mubarak23** [comment]
> How does this fix the test?

i use start and stop prank to changes the caller's address and contract address to execute the function on

**Comment by mubarak23** [comment]
with the test data, 

bip340::verify  is returning this 

`
result of bip340::verify is : false`

**Comment by maciejka** [comment]
> changing the hash value will fix the test

I already fixed it.

**Comment by mubarak23** [comment]
> > changing the hash value will fix the test
> 
> No need to use pranks here. I already fixed it.

awesome, welldone

**Pull request merged**
