### PR TITLE
feat: Map nostr public key to DNS joyboy.community using NIP-05

### PR DESCRIPTION
**Pull request by Gift-Naomi**

### CODE REVIEW

**Review by maciejka — COMMENTED** [review]
Hey, thanks for the pr.

Little question: did you check CORS related behaviour: https://github.com/nostr-protocol/nips/blob/master/05.md#allowing-access-from-javascript-apps?

**Comment by maciejka** [comment]
What did you check exactly?

**Comment by Gift-Naomi** [comment]
I checked the CORs related behaviour here  https://github.com/nostr-protocol/nips/blob/master/05.md#allowing-access-from-javascript-apps its says `/.well-known/nostr.json ` needs to be served with `Access-Control-Allow-Origin: *` but I think that has to be done from the backend

**Comment by maciejka** [comment]
Description of issue #13 changed, so different approach will be necessary.

**Pull request closed without merging**
