### PR TITLE
Redesign/103 post creation page re design

### PR DESCRIPTION
**Pull request by josephchimebuka**
I completed the redesign for the post-creation page. I created a new branch to make it easier to review

### CODE REVIEW

**Review by MSghais — CHANGES_REQUESTED** [review]
Can you add the icons using: 

https://icons.expo.fyi/Index


Also, you have merge conflicts that need to be fixed before please.

**Comment by MSghais** [comment]
> Can you add the icons using:
> 
> https://icons.expo.fyi/Index
> 
> Also, you have merge conflicts that need to be fixed before please.

@ugur-eren questions, if we have difficulties finding the design of the same item here: https://icons.expo.fyi/Index, 
maybe we can get a similar one, or let's stay with a .png or better a .svg?

**Comment by josephchimebuka** [comment]
I think the reason for the merge conflict was that my branch was 4 changes behind I have synced the changes now it is up to date with the main

**Comment by Israelrex9** [comment]
Hey @josephchimebuka  @MSghais 
Do you need the svg of the icons I used on figma?

**Pull request closed without merging**
